### ISSUE TITLE
ImportError: libcoinblas.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Rlahuerta** [xuy/pyipopt#25]
Hi,

I am trying to install, I did I procedure described without warning or errors, but when I try to call "import pyipopt" the following error appears:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyipopt/__init__.py", line 16, in <module>
    from pyipoptcore import *
ImportError: libcoinblas.so.1: cannot open shared object file: No such file or directory

It is very strange to me because in my virtual-machine (VM) the installation is working perfectly, but now I created a dual boot using Ubuntu 14.04 LTS (the same version from VM).

Any idea what’s going on?

Cheers,

**Comment by salazardetroya** [comment]
I think you need to use the Blas library within Ipopt. Add this flag to the ./configure for IpOpt --with-blas=BUILD and --with-lapack=BUILD.

**Comment by FlorianShepherd** [comment]
Is this working for you?

I have the same problem with libcoinhsl.so or libcoinmumps (depending what I chose in setup.py)

```
  File "/home/florian/anaconda3/lib/python3.6/site-packages/pyipopt/__init__.py", line 16, in <module>
    from pyipoptcore import *
ImportError: libcoinmumps.so.1: cannot open shared object file: No such file or directory

```

As far as I understand the manual, Ipopt automatically compiles with mumps or hsl if provided? The IPopt C++ example (hs07) runs fine. The libraries are also present in /usr/local/lib
