### ISSUE TITLE
Symbol not found: __gfortran_adjustl on mac OS El Capitan

### ISSUE THREAD

**Issue by cgavriluta** [xuy/pyipopt#28]
I am trying to install pyipopt on mac OS X 10.11.1 El Capitan. 
I am just getting started with UNIX systems, but I managed to compile the Ipopt library from source and the hs071_c example runs without any issues. 
I run the instalation of pyipopt as instructed. Changed the setup.py file in order to point to the Ipopt library, and the build and install didn't throw any errors. However, when i try to test it and import pyipopt, it throws: 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyipopt/__init__.py", line 16, in <module>
    from pyipoptcore import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyipopt/pyipoptcore.cpython-35m-darwin.so, 2): Symbol not found: __gfortran_adjustl
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyipopt/pyipoptcore.cpython-35m-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pyipopt/pyipoptcore.cpython-35m-darwin.so`

Please let me know if you know of any successful installations on El Capitan. 
Thanks.

**Comment by cgavriluta** [comment]
Managed to make it work. It was a library-related issue as stated in the instructions.
